before_script:
  - export PATH=$PATH:$MAVEN_HOME/bin:$JAVA_HOME/bin
  - java -version
  - mvn -v
  - echo $HOME

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - deploy
  - doc
  - site

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests -Dorg.slf4j.simpleLogger.defaultLogLevel=$ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL
  artifacts:
    paths:
      - target/*
      - ./*/target/*
    expire_in: 2 days

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar surefire:test -Dorg.slf4j.simpleLogger.defaultLogLevel=$ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL
  artifacts:
    expire_in: 2 days

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar deploy:deploy -Dorg.slf4j.simpleLogger.defaultLogLevel=$ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL
  artifacts:
    expire_in: 2 days

javadoc:
  stage: doc
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar javadoc:aggregate-no-fork -Dorg.slf4j.simpleLogger.defaultLogLevel=$ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL
  allow_failure: true
  artifacts:
    expire_in: 2 days

site:
  stage: site
  script:
    - mvn $MAVEN_CLI_OPTS site-deploy -Dorg.slf4j.simpleLogger.defaultLogLevel=$ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL
  artifacts:
    expire_in: 2 days

sonar:
  stage: site
  dependencies:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -Dorg.slf4j.simpleLogger.defaultLogLevel=$ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.host.url=http://$SONAR_SERVER:9000 -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 2 days
