before_script:
  - export PATH=$PATH:$MAVEN_HOME/bin:$JAVA_HOME/bin
  - java -version
  - mvn -v
  - pwd
  - echo $HOME
  - echo $MAVEN_CLI_OPTS
  - echo $ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL

stages:
  - build
  - test
  - deploy
  - doc
  - site

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
  artifacts:
    paths:
      - target/*
      - ./*/target/*
    expire_in: 2 days

form-simpleunit:
  stage: build
  script:
    - cd tex/
    - xelatex -halt-on-error simpleUnit.tex
    - xelatex -halt-on-error simpleUnit.tex
    - htxelatex simpleUnit.tex xhtml
    - zip simpleUnit.zip simpleUnit.pdf simpleUnit.html simpleUnit.css simpleUnit*x.svg
    - scp simpleUnit.zip $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER:$PUBLIC_SITE_SERVER_PATH/su
    - ssh $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER "cd $PUBLIC_SITE_SERVER_PATH/su ; unzip -o simpleUnit.zip ; mv simpleUnit.html index.html ; rm simpleUnit.zip"
  artifacts:
    paths:
      - tex/simpleUnit.pdf
    expire_in: 2 days

form-bibliograpi:
  stage: build
  script:
    - cd tex/
    - xelatex -halt-on-error bibliograpi.tex
    - xelatex -halt-on-error bibliograpi.tex
    - htxelatex bibliograpi.tex xhtml
    - zip bibliograpi.zip bibliograpi.pdf bibliograpi.html bibliograpi.css bibliograpi*x.svg
    - scp bibliograpi.zip $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER:$PUBLIC_SITE_SERVER_PATH/bibapi
    - ssh $PUBLIC_SITE_USER@$PUBLIC_SITE_SERVER "cd $PUBLIC_SITE_SERVER_PATH/bibapi ; unzip -o bibliograpi.zip ; mv bibliograpi.html index.html ; rm bibliograpi.zip"
  artifacts:
    paths:
      - tex/bibliograpi.pdf
    expire_in: 2 days

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar surefire:test
  artifacts:
    expire_in: 2 days

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar deploy:deploy
  environment:
    name: maven
    url: http://cosmoloj.com/maven/com/cosmoloj/cosmoloj/maven-metadata.xml
  artifacts:
    expire_in: 2 days

github:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.resolver.transport=wagon jar:jar deploy:deploy -Pgithub
  artifacts:
    expire_in: 2 days

javadoc:
  stage: doc
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar javadoc:aggregate-no-fork
  artifacts:
    expire_in: 2 days

site:
  stage: site
  script:
    - mvn $MAVEN_CLI_OPTS clean install
    - mvn $MAVEN_CLI_OPTS site-deploy
    - curl --silent http://cosmoloj.com/cosmoloj/ | grep publishDate
    - curl --silent http://cosmoloj.com/cosmoloj/apidocs/index.html | grep Generated
  artifacts:
    expire_in: 2 days
  environment:
    name: site
    url: http://cosmoloj.com/cosmoloj/

sonar:
  stage: site
  script:
    - mvn $MAVEN_CLI_OPTS clean install
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.host.url=http://$SONAR_SERVER:9000 -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 2 days
  environment:
    name: sonar
    url: http://sonar.romiosyne.net/dashboard?id=cosmoloj
