before_script:
  - export PATH=$PATH:$MAVEN_HOME/bin:$JAVA_HOME/bin
  - java -version
  - mvn -v
  - pwd
  - echo $HOME
  - echo $MAVEN_CLI_OPTS
  - echo $ORG_SLF4J_SIMPLELOGGER_DEFAULTLOGLEVEL

stages:
  - build
  - test
  - deploy
  - doc
  - site

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
  artifacts:
    paths:
      - target/*
      - ./*/target/*
    expire_in: 2 days

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar surefire:test
  artifacts:
    expire_in: 2 days

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar deploy:deploy
  artifacts:
    expire_in: 2 days

javadoc:
  stage: doc
  script:
    - mvn $MAVEN_CLI_OPTS jar:jar javadoc:aggregate-no-fork
  artifacts:
    expire_in: 2 days

site:
  stage: site
  script:
    - mvn $MAVEN_CLI_OPTS site-deploy
  artifacts:
    expire_in: 2 days

sonar:
  stage: site
  script:
    - mvn $MAVEN_CLI_OPTS clean install
    - mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.host.url=http://$SONAR_SERVER:9000 -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 2 days
