name: build
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: s4u/setup-maven-action@v1.13.0
        with:
          distribution: 'oracle'
          java-version: '24'
          maven-version: '3.9.11'
      - run: java -version
      - run: mvn -v
      - run: mvn clean install -DskipTests
