name: unit_simple
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - actions_try

jobs:
  build__unit_simple:
    runs-on: ubuntu-latest
    steps:
      - run: java -version
      - run: mvn -v
